name: .NET Core

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish TimeCalc/TimeCalc.csproj --configuration Release --no-restore
    - name: Copy to blob storage
      uses: Azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: >
          az storage blob upload-batch
          -s $GITHUB_WORKSPACE/src/TimeCalc/bin/Release/netstandard2.1/publish/wwwroot
          -d \$web
          --connection-string '${{ secrets.STORAGE_CONNECTION_STRING }}'

    - name: Azure service principal login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Purge CDN
      run:
        az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait
    - name: Azure service principal logout
      run: |
        az logout
